### ISSUE TITLE
Symbols in db password can break install

### ISSUE THREAD

**Issue by busheezy** [maxhoesel-ansible/ansible-collection-pterodactyl#161]
I was having some trouble getting the DB to connect. I realized the symbols weren't being wrapped in quotes once put in the .env.

Thanks for everything.

**Comment by Zerka30** [comment]
I have the same issue 😭 . Fortunately, this issue was open

**Comment by Zerka30** [comment]
I fix it in https://github.com/maxhoesel-ansible/ansible-collection-pterodactyl/pull/166

**Comment by maxhoesel** [comment]
Hi, thanks for the PR! Could you tell me which symbols are causing this issue for you? I'd like to add a test case to make sure this keeps working into the future

**Comment by Zerka30** [comment]
> Hi, thanks for the PR! Could you tell me which symbols are causing this issue for you? I'd like to add a test case to make sure this keeps working into the future

In my case its was '%'

**Comment by maxhoesel** [comment]
Fixed in #166, thanks for reporting this issue!
